version: "3.5"
services:
  mysql-db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gokul
      MYSQL_PASSWORD: gokul656
      MYSQL_DATABASE: springsdb

  zervrer:
    depends_on:
      - mysql-db
    ports:
      - 8080:8080
    build: "./"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3307/springsdb&useSSL=false
      SPRING_DATASOURCE_USERNAME: gokul
      SPRING_DATASOURCE_PASSWORD: gokul656
